complexity:
  # Compose functions tend to be longer and have a lot of parameters
  LongMethod:
    allowedLines: 150
  LongParameterList:
    ignoreDefaultParameters: true

naming:
  # Compose functions are uppercase
  FunctionNaming:
    functionPattern: "[a-zA-Z0-9]*"
  # Ofter files with Composable function start with accessory interfaces
  MatchingDeclarationName:
    active: false

style:
  # Library is still in alpha, let's allow TODOs
  ForbiddenComment:
    comments: [ ]
  WildcardImport:
    excludeImports:
      - io.github.gardencompose.adw.components.*
      - io.github.gardencompose.gtk.components.*
  MagicNumber:
    excludes:
      - "**/test/**"
      - "**/tests/**"

ktlint:
  NoWildcardImports:
    packagesToUseImportOnDemandProperty:
      "io.github.gardencompose.adw.components.*,io.github.gardencompose.gtk.components.*"
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
  Filename:
    # Examples have a number prepended to the file name, to ensure users can read them in order
    excludes:
      - "**/examples/**"
  FunctionSignature:
    active: false
  ClassSignature:
    active: false
  FunctionExpressionBody:
    active: false

Compose:
  active: true
  ModifierMissing:
    excludes:
      - "**/test/**"
      - "**/tests/**"
  MutableStateParam:
    excludes:
      - "**/test/**"
      - "**/tests/**"
  CompositionLocalAllowlist:
    active: true
    allowedCompositionLocals:
      - LocalApplication
      - LocalApplicationWindow
